# Generated by Django 6.0.7 on 2026-07-09 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_loanrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankuser',
            options={'verbose_name': 'Bank User', 'verbose_name_plural': 'Bank Users'},
        ),
        migrations.AlterModelOptions(
            name='loanrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='bankuser',
            name='face_signature',
            field=models.TextField(blank=True, help_text='Mock biometric hash for FaceID simulation', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Transfer', 'Transfer'), ('Bill Split', 'Bill Split'), ('Loan', 'Loan')], default='Transfer', max_length=20),
        ),
        migrations.AlterField(
            model_name='bankuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
