# Generated by Django 6.0.7 on 2026-07-10 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_bankuser_options_alter_loanrequest_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=50)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='bankuser',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='bankuser',
            name='face_signature',
        ),
        migrations.AddField(
            model_name='bankuser',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=5000.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bankuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bankuser',
            name='roll_number',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Enter your University Roll No. starting with 240122 (Must be exactly 13 digits).', regex='^240122\\d{7}$')]),
        ),
    ]
