# Generated by Django 6.0.7 on 2026-07-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_paymentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankuser',
            name='face_signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
